name: Release and Deploy Contract

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  workflow_dispatch:
    inputs:
      generate-tag:
        description: 'Generate a new tag'
        required: true
        default: 'true'
      custom-tag: 
        description: 'Custom tag to be used if generate-tag is false'
        required: false
        default: ''
      network: 
        description: 'Network to deploy contract to'
        required: true
        default: 'holesky'
        type: choice
        options:
          - holesky
      environment:
        description: 'Environment to deploy contract to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev

jobs:
  auto-release:
    uses: init4tech/actions/.github/workflows/auto-release.yml@main
    permissions:
      contents: write    
    with:
      generate-tag: true
      custom-tag: ${{ github.event.inputs.custom-tag }}
  deploy-contract:
    uses: init4tech/actions/.github/workflows/solidity-deployment.yml@main
    needs: auto-release
    permissions:
      contents: write
      id-token: write
    with:
      network: holesky
      environment: dev
      forge-deployment-contract: ZenithScript
      forge-deployment-script-file: Zenith.s.sol
      forge-deployment-signature: "deploy(uint256,address,address)"
      forge-deployment-params: "17001 0x11Aa4EBFbf7a481617c719a2Df028c9DA1a219aa 0x29403F107781ea45Bf93710abf8df13F67f2008f"
      etherscan-url: https://holesky.etherscan.io
      chain-id: 17000
      deployer-address: ${{ inputs.HOLESKY_DEPLOYER_ADDRESS }}
    secrets:
      aws-deployer-role: ${{ secrets.AWS_DEPLOYER_ROLE }}
      kms-key-id: ${{ secrets.HOLESKY_DEPLOYER_KEY_ID }}
      rpc-url: ${{ secrets.HOLESKY_RPC_URL }}
      etherscan-api-key: ${{ secrets.ETHERSCAN_API_KEY }}